<?php

// $Id$

/**
 * Implements hook_menu().
 */
function daskboard_menu() {
  $items['daskboard'] = array(
    'title' => 'daskboard',
    'page callback' => 'daskboard_page',
    'access callback' => 'user_is_logged_in',
  );

  $items['daskboard_mockup'] = array(
    'title' => 'daskboard',
    'page callback' => 'daskboard_page_mockup',
    'access callback' => 'user_is_logged_in',
  );
  
  return $items;
}

/**
 * Implements hook_init().
 */
function daskboard_init() {
  drupal_add_css(drupal_get_path('module', 'daskboard') . '/daskboard.css');
}

function daskboard_page($uid = 0) {
  $node = node_load(1);

  $build = array();
  $build['queue'] = array(
    '#theme' => 'taskqueue',
  );
  $nodes = node_load_multiple(array(), array('type' => 'task'));
  $build['queue'] += node_view_multiple($nodes, 'teaser');
  
  return $build;
}

function daskboard_page_mockup() {
  $node = node_load(1);

  $build = array();
  for ($j = 0; $j < 3; $j++) {
    $build[$j] = array(
      '#theme' => 'taskqueue',
    );
    for ($i = 0; $i < ($j == 1 ? 2 : 5); $i++) {
      $build[$j]['nodes'][] = node_view($node, 'teaser');
    }
  }
  return $build;
}

/**
 * Implements hook_theme().
 */
function daskboard_theme() {
  return array(
    'taskqueue' => array(
      'render element' => 'elements',
      'template' => 'taskqueue',
    ),
  );
}

function template_preprocess_taskqueue(&$variables) {
  $variables['nodes'] = $variables['elements']['nodes'];
  $variables['title'] = isset($variables['elements']['#title']) ? $variables['elements']['#title'] : '';
}
