<?php

// $Id$

/**
 * Implements hook_menu().
 */
function daskboard_menu() {
  $items['daskboard'] = array(
    'title' => 'daskboard',
    'page callback' => 'daskboard_page',
    'access callback' => 'user_is_logged_in',
  );

  $items['daskboard_mockup'] = array(
    'title' => 'daskboard',
    'page callback' => 'daskboard_page_mockup',
    'access callback' => 'user_is_logged_in',
  );
  
  return $items;
}

/**
 * Implements hook_init().
 */
function daskboard_init() {
  drupal_add_css(drupal_get_path('module', 'daskboard') . '/daskboard.css');
}

function daskboard_page($uid = 0) {
  dpm(field_info_field('depends_on'));
  //$node = node_load(2);
  //task_update_dependent($node);
  //dpm(    $field = field_read_instance('node', 'depends_on', 'task'));
  // dpm(field_attach_query(25, array(array('type', 'node'), array('bundle', 'task'), array('nid', 1))));
  return '';
}

function daskboard_page_mockup() {
  drupal_add_css(drupal_get_path('module', 'daskboard') . '/daskboard.css');
  $node = node_load(1);

  $build = array();
  for ($j = 0; $j < 3; $j++) {
    $build[$j] = array(
      '#theme' => 'taskqueue',
    );
    for ($i = 0; $i < ($j == 1 ? 2 : 5); $i++) {
      $build[$j]['items'][] = node_view($node, 'taskcard');
    }
  }
  return $build;
}

/**
 * Implements hook_theme().
 */
function daskboard_theme() {
  return array(
    'taskqueue' => array(
      'render element' => 'elements',
      'template' => 'taskqueue',
    ),
  );
}

function template_preprocess_taskqueue(&$variables) {
  $variables['items'] = $variables['elements']['items'];
  $variables['title'] = isset($variables['elements']['#title']) ? $variables['elements']['#title'] : '';
}
